apiVersion: sources.eventing.knative.dev/v1alpha1
kind: PrometheusSource
metadata:
  name: prometheus-source
spec:
  serverURL: https://prometheus-k8s.openshift-monitoring.svc:9091
  promQL: ALERTS
  authTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  caCertConfigMap: openshift-service-serving-signer-cabundle
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
