apiVersion: sources.eventing.knative.dev/v1alpha1
kind: PrometheusSource
metadata:
  name: prometheus-source
spec:
  serverURL: http://demo.robustperception.io:9090
  promQL: ALERTS
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
