apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: gcp-pubsub-transformer
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: github.com/knative/eventing-sources/contrib/gcppubsub/cmd/transformer
