apiVersion: v1
kind: ServiceAccount
metadata:
  name: gcppubsub
secrets:
- name: gcppubsub-source-key
---
apiVersion: v1
kind: Secret
metadata:
  name: gcppubsub-source-key
type: Opaque
data:
  'key.json': ""