# Channel for testing events.

apiVersion: messaging.knative.dev/v1alpha1
kind: Channel
metadata:
  name: awssqs-test
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: InMemoryChannel

---

# Subscription from the AWS SQS Source's output Channel to the Knative Service below.

apiVersion: messaging.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: awssqs-source-display
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: Channel
    name: awssqs-test
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: awssqs-event-display

---

# This is a very simple Knative Service that prints the input event to its log.

apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: awssqs-event-display
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: ko://knative.dev/eventing-contrib/cmd/event_display
