/*
Copyright 2018 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/knative/eventing-sources/pkg/apis/sources/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCloudEventIngresses implements CloudEventIngressInterface
type FakeCloudEventIngresses struct {
	Fake *FakeSourcesV1alpha1
	ns   string
}

var cloudeventingressesResource = schema.GroupVersionResource{Group: "sources.eventing.knative.dev", Version: "v1alpha1", Resource: "cloudeventingresses"}

var cloudeventingressesKind = schema.GroupVersionKind{Group: "sources.eventing.knative.dev", Version: "v1alpha1", Kind: "CloudEventIngress"}

// Get takes name of the cloudEventIngress, and returns the corresponding cloudEventIngress object, and an error if there is any.
func (c *FakeCloudEventIngresses) Get(name string, options v1.GetOptions) (result *v1alpha1.CloudEventIngress, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cloudeventingressesResource, c.ns, name), &v1alpha1.CloudEventIngress{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CloudEventIngress), err
}

// List takes label and field selectors, and returns the list of CloudEventIngresses that match those selectors.
func (c *FakeCloudEventIngresses) List(opts v1.ListOptions) (result *v1alpha1.CloudEventIngressList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cloudeventingressesResource, cloudeventingressesKind, c.ns, opts), &v1alpha1.CloudEventIngressList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CloudEventIngressList{ListMeta: obj.(*v1alpha1.CloudEventIngressList).ListMeta}
	for _, item := range obj.(*v1alpha1.CloudEventIngressList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cloudEventIngresses.
func (c *FakeCloudEventIngresses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cloudeventingressesResource, c.ns, opts))

}

// Create takes the representation of a cloudEventIngress and creates it.  Returns the server's representation of the cloudEventIngress, and an error, if there is any.
func (c *FakeCloudEventIngresses) Create(cloudEventIngress *v1alpha1.CloudEventIngress) (result *v1alpha1.CloudEventIngress, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cloudeventingressesResource, c.ns, cloudEventIngress), &v1alpha1.CloudEventIngress{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CloudEventIngress), err
}

// Update takes the representation of a cloudEventIngress and updates it. Returns the server's representation of the cloudEventIngress, and an error, if there is any.
func (c *FakeCloudEventIngresses) Update(cloudEventIngress *v1alpha1.CloudEventIngress) (result *v1alpha1.CloudEventIngress, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cloudeventingressesResource, c.ns, cloudEventIngress), &v1alpha1.CloudEventIngress{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CloudEventIngress), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCloudEventIngresses) UpdateStatus(cloudEventIngress *v1alpha1.CloudEventIngress) (*v1alpha1.CloudEventIngress, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(cloudeventingressesResource, "status", c.ns, cloudEventIngress), &v1alpha1.CloudEventIngress{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CloudEventIngress), err
}

// Delete takes name of the cloudEventIngress and deletes it. Returns an error if one occurs.
func (c *FakeCloudEventIngresses) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(cloudeventingressesResource, c.ns, name), &v1alpha1.CloudEventIngress{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCloudEventIngresses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cloudeventingressesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.CloudEventIngressList{})
	return err
}

// Patch applies the patch and returns the patched cloudEventIngress.
func (c *FakeCloudEventIngresses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CloudEventIngress, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cloudeventingressesResource, c.ns, name, data, subresources...), &v1alpha1.CloudEventIngress{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CloudEventIngress), err
}
