/*
Copyright 2018 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/knative/eventing-sources/pkg/apis/sources/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEdgeSources implements EdgeSourceInterface
type FakeEdgeSources struct {
	Fake *FakeSourcesV1alpha1
	ns   string
}

var edgesourcesResource = schema.GroupVersionResource{Group: "sources.eventing.knative.dev", Version: "v1alpha1", Resource: "edgesources"}

var edgesourcesKind = schema.GroupVersionKind{Group: "sources.eventing.knative.dev", Version: "v1alpha1", Kind: "EdgeSource"}

// Get takes name of the edgeSource, and returns the corresponding edgeSource object, and an error if there is any.
func (c *FakeEdgeSources) Get(name string, options v1.GetOptions) (result *v1alpha1.EdgeSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(edgesourcesResource, c.ns, name), &v1alpha1.EdgeSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EdgeSource), err
}

// List takes label and field selectors, and returns the list of EdgeSources that match those selectors.
func (c *FakeEdgeSources) List(opts v1.ListOptions) (result *v1alpha1.EdgeSourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(edgesourcesResource, edgesourcesKind, c.ns, opts), &v1alpha1.EdgeSourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.EdgeSourceList{ListMeta: obj.(*v1alpha1.EdgeSourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.EdgeSourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested edgeSources.
func (c *FakeEdgeSources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(edgesourcesResource, c.ns, opts))

}

// Create takes the representation of a edgeSource and creates it.  Returns the server's representation of the edgeSource, and an error, if there is any.
func (c *FakeEdgeSources) Create(edgeSource *v1alpha1.EdgeSource) (result *v1alpha1.EdgeSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(edgesourcesResource, c.ns, edgeSource), &v1alpha1.EdgeSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EdgeSource), err
}

// Update takes the representation of a edgeSource and updates it. Returns the server's representation of the edgeSource, and an error, if there is any.
func (c *FakeEdgeSources) Update(edgeSource *v1alpha1.EdgeSource) (result *v1alpha1.EdgeSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(edgesourcesResource, c.ns, edgeSource), &v1alpha1.EdgeSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EdgeSource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEdgeSources) UpdateStatus(edgeSource *v1alpha1.EdgeSource) (*v1alpha1.EdgeSource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(edgesourcesResource, "status", c.ns, edgeSource), &v1alpha1.EdgeSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EdgeSource), err
}

// Delete takes name of the edgeSource and deletes it. Returns an error if one occurs.
func (c *FakeEdgeSources) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(edgesourcesResource, c.ns, name), &v1alpha1.EdgeSource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEdgeSources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(edgesourcesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.EdgeSourceList{})
	return err
}

// Patch applies the patch and returns the patched edgeSource.
func (c *FakeEdgeSources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.EdgeSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(edgesourcesResource, c.ns, name, data, subresources...), &v1alpha1.EdgeSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EdgeSource), err
}
