/*
Copyright 2018 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/knative/eventing-sources/pkg/apis/sources/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBitBucketSources implements BitBucketSourceInterface
type FakeBitBucketSources struct {
	Fake *FakeSourcesV1alpha1
	ns   string
}

var bitbucketsourcesResource = schema.GroupVersionResource{Group: "sources.eventing.knative.dev", Version: "v1alpha1", Resource: "bitbucketsources"}

var bitbucketsourcesKind = schema.GroupVersionKind{Group: "sources.eventing.knative.dev", Version: "v1alpha1", Kind: "BitBucketSource"}

// Get takes name of the bitBucketSource, and returns the corresponding bitBucketSource object, and an error if there is any.
func (c *FakeBitBucketSources) Get(name string, options v1.GetOptions) (result *v1alpha1.BitBucketSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(bitbucketsourcesResource, c.ns, name), &v1alpha1.BitBucketSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BitBucketSource), err
}

// List takes label and field selectors, and returns the list of BitBucketSources that match those selectors.
func (c *FakeBitBucketSources) List(opts v1.ListOptions) (result *v1alpha1.BitBucketSourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(bitbucketsourcesResource, bitbucketsourcesKind, c.ns, opts), &v1alpha1.BitBucketSourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BitBucketSourceList{ListMeta: obj.(*v1alpha1.BitBucketSourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.BitBucketSourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested bitBucketSources.
func (c *FakeBitBucketSources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(bitbucketsourcesResource, c.ns, opts))

}

// Create takes the representation of a bitBucketSource and creates it.  Returns the server's representation of the bitBucketSource, and an error, if there is any.
func (c *FakeBitBucketSources) Create(bitBucketSource *v1alpha1.BitBucketSource) (result *v1alpha1.BitBucketSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(bitbucketsourcesResource, c.ns, bitBucketSource), &v1alpha1.BitBucketSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BitBucketSource), err
}

// Update takes the representation of a bitBucketSource and updates it. Returns the server's representation of the bitBucketSource, and an error, if there is any.
func (c *FakeBitBucketSources) Update(bitBucketSource *v1alpha1.BitBucketSource) (result *v1alpha1.BitBucketSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(bitbucketsourcesResource, c.ns, bitBucketSource), &v1alpha1.BitBucketSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BitBucketSource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBitBucketSources) UpdateStatus(bitBucketSource *v1alpha1.BitBucketSource) (*v1alpha1.BitBucketSource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(bitbucketsourcesResource, "status", c.ns, bitBucketSource), &v1alpha1.BitBucketSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BitBucketSource), err
}

// Delete takes name of the bitBucketSource and deletes it. Returns an error if one occurs.
func (c *FakeBitBucketSources) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(bitbucketsourcesResource, c.ns, name), &v1alpha1.BitBucketSource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBitBucketSources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(bitbucketsourcesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.BitBucketSourceList{})
	return err
}

// Patch applies the patch and returns the patched bitBucketSource.
func (c *FakeBitBucketSources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.BitBucketSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(bitbucketsourcesResource, c.ns, name, data, subresources...), &v1alpha1.BitBucketSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BitBucketSource), err
}
