# this fixes the auto-detected object, we use a string in the stored object but
# a wrapper object for time at runtime.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gcppubsubsources.sources.eventing.knative.dev
spec:
  validation:
    openAPIV3Schema:
      properties:
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    type: string
