# Copyright 2020 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ceph-source-webhook
  labels:
    notifications.ceph.com/release: devel
rules:
  # Sources admin
  - apiGroups:
      - notifications.ceph.com
    resources:
      - cephsources
    verbs: &everything
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Sources finalizer
  - apiGroups:
      - notifications.ceph.com
    resources:
      - cephsources/finalizers
    verbs: *everything

  # Source statuses update
  - apiGroups:
      - notifications.ceph.com
    resources:
      - cephsources/status
    verbs:
      - get
      - update
      - patch

  # Deployments admin
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs: *everything

  # Secrets read
  - apiGroups:
      - ""
    resources:
      - secrets
      - services
    verbs:
      - get
      - list
      - watch

  # Namespace labelling for webhook
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
      - patch

  # Events admin
  - apiGroups:
      - ""
    resources:
      - events
      - configmaps
    verbs: *everything

  # EventTypes admin
  - apiGroups:
      - eventing.knative.dev
    resources:
      - eventtypes
    verbs: *everything

  # For manipulating certs into secrets.
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "get"
      - "create"
      - "update"
      - "list"
      - "watch"

  # For actually registering our webhook.
  - apiGroups:
      - "admissionregistration.k8s.io"
    resources:
      - "mutatingwebhookconfigurations"
      - "validatingwebhookconfigurations"
    verbs: *everything
