apiVersion: messaging.knative.dev/v1beta1
kind: Channel
metadata:
  name: ceph-event-channel
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1beta1
    kind: InMemoryChannel
---
apiVersion: messaging.knative.dev/v1beta1
kind: Subscription
metadata:
  name: ceph-source-display
spec:
  channel:
    apiVersion: messaging.knative.dev/v1beta1
    kind: Channel
    name: ceph-event-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: ceph-event-display
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ceph-event-display
spec:
  template:
    spec:
      containers:
        - name: ceph-display-container
          image: ko://knative.dev/eventing-contrib/cmd/event_display
