apiVersion: messaging.knative.dev/v1alpha1
kind: Channel
metadata:
  name: ceph-event-channel
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: InMemoryChannel
---
apiVersion: messaging.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: ceph-source-display
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: Channel
    name: ceph-event-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: ceph-event-display
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: ceph-event-display
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: knative.dev/eventing-contrib/cmd/event_display
