apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceph-bucket-notification-source
  labels:
    app: ceph-source
spec:
  selector:
    matchLabels:
      app: ceph-source
  template:
    metadata:
      labels:
        app: ceph-source
    spec:
      containers:
        - name: ceph-source
          image: ko://knative.dev/eventing-contrib/ceph/cmd/receive_adapter
          env:
            - name: PORT
              value: "19090"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: METRICS_DOMAIN
              value: "knative.dev/sources"
            - name: K_METRICS_CONFIG
            - name: K_LOGGING_CONFIG
          ports:
            - containerPort: 19090

---

apiVersion: sources.knative.dev/v1alpha2
kind: SinkBinding
metadata:
  name: ceph-source-sinkbinding
spec:
  subject:
    apiVersion: apps/v1
    kind: Deployment
    selector:
      matchLabels:
        app: ceph-source
  sink:
    ref:
      apiVersion: messaging.knative.dev/v1beta1
      kind: Channel
      name: ceph-event-channel
