/*
Copyright 2018 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/knative/eventing-sources/pkg/apis/sources/v1alpha1"
	scheme "github.com/knative/eventing-sources/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CloudEventIngressesGetter has a method to return a CloudEventIngressInterface.
// A group's client should implement this interface.
type CloudEventIngressesGetter interface {
	CloudEventIngresses(namespace string) CloudEventIngressInterface
}

// CloudEventIngressInterface has methods to work with CloudEventIngress resources.
type CloudEventIngressInterface interface {
	Create(*v1alpha1.CloudEventIngress) (*v1alpha1.CloudEventIngress, error)
	Update(*v1alpha1.CloudEventIngress) (*v1alpha1.CloudEventIngress, error)
	UpdateStatus(*v1alpha1.CloudEventIngress) (*v1alpha1.CloudEventIngress, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.CloudEventIngress, error)
	List(opts v1.ListOptions) (*v1alpha1.CloudEventIngressList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CloudEventIngress, err error)
	CloudEventIngressExpansion
}

// cloudEventIngresses implements CloudEventIngressInterface
type cloudEventIngresses struct {
	client rest.Interface
	ns     string
}

// newCloudEventIngresses returns a CloudEventIngresses
func newCloudEventIngresses(c *SourcesV1alpha1Client, namespace string) *cloudEventIngresses {
	return &cloudEventIngresses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cloudEventIngress, and returns the corresponding cloudEventIngress object, and an error if there is any.
func (c *cloudEventIngresses) Get(name string, options v1.GetOptions) (result *v1alpha1.CloudEventIngress, err error) {
	result = &v1alpha1.CloudEventIngress{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cloudeventingresses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CloudEventIngresses that match those selectors.
func (c *cloudEventIngresses) List(opts v1.ListOptions) (result *v1alpha1.CloudEventIngressList, err error) {
	result = &v1alpha1.CloudEventIngressList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cloudeventingresses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cloudEventIngresses.
func (c *cloudEventIngresses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("cloudeventingresses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a cloudEventIngress and creates it.  Returns the server's representation of the cloudEventIngress, and an error, if there is any.
func (c *cloudEventIngresses) Create(cloudEventIngress *v1alpha1.CloudEventIngress) (result *v1alpha1.CloudEventIngress, err error) {
	result = &v1alpha1.CloudEventIngress{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("cloudeventingresses").
		Body(cloudEventIngress).
		Do().
		Into(result)
	return
}

// Update takes the representation of a cloudEventIngress and updates it. Returns the server's representation of the cloudEventIngress, and an error, if there is any.
func (c *cloudEventIngresses) Update(cloudEventIngress *v1alpha1.CloudEventIngress) (result *v1alpha1.CloudEventIngress, err error) {
	result = &v1alpha1.CloudEventIngress{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cloudeventingresses").
		Name(cloudEventIngress.Name).
		Body(cloudEventIngress).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *cloudEventIngresses) UpdateStatus(cloudEventIngress *v1alpha1.CloudEventIngress) (result *v1alpha1.CloudEventIngress, err error) {
	result = &v1alpha1.CloudEventIngress{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cloudeventingresses").
		Name(cloudEventIngress.Name).
		SubResource("status").
		Body(cloudEventIngress).
		Do().
		Into(result)
	return
}

// Delete takes name of the cloudEventIngress and deletes it. Returns an error if one occurs.
func (c *cloudEventIngresses) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cloudeventingresses").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cloudEventIngresses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cloudeventingresses").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched cloudEventIngress.
func (c *cloudEventIngresses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CloudEventIngress, err error) {
	result = &v1alpha1.CloudEventIngress{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("cloudeventingresses").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
