/*
Copyright 2018 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/knative/eventing-sources/pkg/apis/sources/v1alpha1"
	scheme "github.com/knative/eventing-sources/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CloudEventsIngressSourcesGetter has a method to return a CloudEventsIngressSourceInterface.
// A group's client should implement this interface.
type CloudEventsIngressSourcesGetter interface {
	CloudEventsIngressSources(namespace string) CloudEventsIngressSourceInterface
}

// CloudEventsIngressSourceInterface has methods to work with CloudEventsIngressSource resources.
type CloudEventsIngressSourceInterface interface {
	Create(*v1alpha1.CloudEventsIngressSource) (*v1alpha1.CloudEventsIngressSource, error)
	Update(*v1alpha1.CloudEventsIngressSource) (*v1alpha1.CloudEventsIngressSource, error)
	UpdateStatus(*v1alpha1.CloudEventsIngressSource) (*v1alpha1.CloudEventsIngressSource, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.CloudEventsIngressSource, error)
	List(opts v1.ListOptions) (*v1alpha1.CloudEventsIngressSourceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CloudEventsIngressSource, err error)
	CloudEventsIngressSourceExpansion
}

// cloudEventsIngressSources implements CloudEventsIngressSourceInterface
type cloudEventsIngressSources struct {
	client rest.Interface
	ns     string
}

// newCloudEventsIngressSources returns a CloudEventsIngressSources
func newCloudEventsIngressSources(c *SourcesV1alpha1Client, namespace string) *cloudEventsIngressSources {
	return &cloudEventsIngressSources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cloudEventsIngressSource, and returns the corresponding cloudEventsIngressSource object, and an error if there is any.
func (c *cloudEventsIngressSources) Get(name string, options v1.GetOptions) (result *v1alpha1.CloudEventsIngressSource, err error) {
	result = &v1alpha1.CloudEventsIngressSource{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cloudeventsingresssources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CloudEventsIngressSources that match those selectors.
func (c *cloudEventsIngressSources) List(opts v1.ListOptions) (result *v1alpha1.CloudEventsIngressSourceList, err error) {
	result = &v1alpha1.CloudEventsIngressSourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cloudeventsingresssources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cloudEventsIngressSources.
func (c *cloudEventsIngressSources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("cloudeventsingresssources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a cloudEventsIngressSource and creates it.  Returns the server's representation of the cloudEventsIngressSource, and an error, if there is any.
func (c *cloudEventsIngressSources) Create(cloudEventsIngressSource *v1alpha1.CloudEventsIngressSource) (result *v1alpha1.CloudEventsIngressSource, err error) {
	result = &v1alpha1.CloudEventsIngressSource{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("cloudeventsingresssources").
		Body(cloudEventsIngressSource).
		Do().
		Into(result)
	return
}

// Update takes the representation of a cloudEventsIngressSource and updates it. Returns the server's representation of the cloudEventsIngressSource, and an error, if there is any.
func (c *cloudEventsIngressSources) Update(cloudEventsIngressSource *v1alpha1.CloudEventsIngressSource) (result *v1alpha1.CloudEventsIngressSource, err error) {
	result = &v1alpha1.CloudEventsIngressSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cloudeventsingresssources").
		Name(cloudEventsIngressSource.Name).
		Body(cloudEventsIngressSource).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *cloudEventsIngressSources) UpdateStatus(cloudEventsIngressSource *v1alpha1.CloudEventsIngressSource) (result *v1alpha1.CloudEventsIngressSource, err error) {
	result = &v1alpha1.CloudEventsIngressSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cloudeventsingresssources").
		Name(cloudEventsIngressSource.Name).
		SubResource("status").
		Body(cloudEventsIngressSource).
		Do().
		Into(result)
	return
}

// Delete takes name of the cloudEventsIngressSource and deletes it. Returns an error if one occurs.
func (c *cloudEventsIngressSources) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cloudeventsingresssources").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cloudEventsIngressSources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cloudeventsingresssources").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched cloudEventsIngressSource.
func (c *cloudEventsIngressSources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CloudEventsIngressSource, err error) {
	result = &v1alpha1.CloudEventsIngressSource{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("cloudeventsingresssources").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
