// +build !ignore_autogenerated

/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaAuthSpec) DeepCopyInto(out *KafkaAuthSpec) {
	*out = *in
	if in.BootstrapServers != nil {
		in, out := &in.BootstrapServers, &out.BootstrapServers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Net.DeepCopyInto(&out.Net)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaAuthSpec.
func (in *KafkaAuthSpec) DeepCopy() *KafkaAuthSpec {
	if in == nil {
		return nil
	}
	out := new(KafkaAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaBinding) DeepCopyInto(out *KafkaBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaBinding.
func (in *KafkaBinding) DeepCopy() *KafkaBinding {
	if in == nil {
		return nil
	}
	out := new(KafkaBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KafkaBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaBindingList) DeepCopyInto(out *KafkaBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KafkaBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaBindingList.
func (in *KafkaBindingList) DeepCopy() *KafkaBindingList {
	if in == nil {
		return nil
	}
	out := new(KafkaBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KafkaBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaBindingSpec) DeepCopyInto(out *KafkaBindingSpec) {
	*out = *in
	in.BindingSpec.DeepCopyInto(&out.BindingSpec)
	in.KafkaAuthSpec.DeepCopyInto(&out.KafkaAuthSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaBindingSpec.
func (in *KafkaBindingSpec) DeepCopy() *KafkaBindingSpec {
	if in == nil {
		return nil
	}
	out := new(KafkaBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaBindingStatus) DeepCopyInto(out *KafkaBindingStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaBindingStatus.
func (in *KafkaBindingStatus) DeepCopy() *KafkaBindingStatus {
	if in == nil {
		return nil
	}
	out := new(KafkaBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaNetSpec) DeepCopyInto(out *KafkaNetSpec) {
	*out = *in
	in.SASL.DeepCopyInto(&out.SASL)
	in.TLS.DeepCopyInto(&out.TLS)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaNetSpec.
func (in *KafkaNetSpec) DeepCopy() *KafkaNetSpec {
	if in == nil {
		return nil
	}
	out := new(KafkaNetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaSASLSpec) DeepCopyInto(out *KafkaSASLSpec) {
	*out = *in
	in.User.DeepCopyInto(&out.User)
	in.Password.DeepCopyInto(&out.Password)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaSASLSpec.
func (in *KafkaSASLSpec) DeepCopy() *KafkaSASLSpec {
	if in == nil {
		return nil
	}
	out := new(KafkaSASLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaTLSSpec) DeepCopyInto(out *KafkaTLSSpec) {
	*out = *in
	in.Cert.DeepCopyInto(&out.Cert)
	in.Key.DeepCopyInto(&out.Key)
	in.CACert.DeepCopyInto(&out.CACert)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaTLSSpec.
func (in *KafkaTLSSpec) DeepCopy() *KafkaTLSSpec {
	if in == nil {
		return nil
	}
	out := new(KafkaTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretValueFromSource) DeepCopyInto(out *SecretValueFromSource) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretValueFromSource.
func (in *SecretValueFromSource) DeepCopy() *SecretValueFromSource {
	if in == nil {
		return nil
	}
	out := new(SecretValueFromSource)
	in.DeepCopyInto(out)
	return out
}
