apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq-controller-manager
  namespace: knative-sources
  labels:
    contrib.eventing.knative.dev/release: devel
secrets:
  - name: rabbitmq-source-key
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-source-key
  namespace: knative-sources
type: Opaque
data:
  'key.json': ""