apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eventing-sources-rabbitmq-controller
  labels:
    contrib.eventing.knative.dev/release: devel
subjects:
  - kind: ServiceAccount
    name: rabbitmq-controller-manager
    namespace: knative-sources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eventing-sources-rabbitmq-controller

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eventing-sources-rabbitmq-controller-addressable-resolver
  labels:
    contrib.eventing.knative.dev/release: devel
subjects:
  - kind: ServiceAccount
    name: rabbitmq-controller-manager
    namespace: knative-sources
# An aggregated ClusterRole for all Addressable CRDs.
# Ref: https://knative.dev/eventing/blob/master/config/200-addressable-resolvers-clusterrole.yaml
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: addressable-resolver