apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-controller
  namespace: knative-sources
  labels:
    contrib.eventing.knative.dev/release: devel
    control-plane: rabbitmq-controller-manager
spec:
  selector:
    control-plane: rabbitmq-controller-manager
  ports:
    - name: https-rabbitmq
      port: 443