apiVersion: sources.eventing.knative.dev/v1alpha1
kind: KafkaEventSource
metadata:
  name: example-kafkaeventsource
spec:
  bootstrap: my-cluster-kafka-bootstrap.myproject.svc.cluster.local:9092
  topic: test
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: testchannel

