apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kafkaeventsources.sources.eventing.knative.dev
spec:
  group: sources.eventing.knative.dev
  names:
    kind: KafkaEventSource
    listKind: KafkaEventSourceList
    plural: kafkaeventsources
    singular: kafkaeventsource
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            bootstrap:
              type: string
            topic:
              type: string
            sink:
              type: object
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    type: object
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            sinkUri:
              type: string
          type: object
      type: object
  version: v1alpha1
