/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "knative.dev/eventing-contrib/ceph/pkg/apis/sources/v1alpha1"
)

// FakeCephSources implements CephSourceInterface
type FakeCephSources struct {
	Fake *FakeBucketnotificationsV1alpha1
	ns   string
}

var cephsourcesResource = schema.GroupVersionResource{Group: "bucketnotifications.ceph.com", Version: "v1alpha1", Resource: "cephsources"}

var cephsourcesKind = schema.GroupVersionKind{Group: "bucketnotifications.ceph.com", Version: "v1alpha1", Kind: "CephSource"}

// Get takes name of the cephSource, and returns the corresponding cephSource object, and an error if there is any.
func (c *FakeCephSources) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CephSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cephsourcesResource, c.ns, name), &v1alpha1.CephSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CephSource), err
}

// List takes label and field selectors, and returns the list of CephSources that match those selectors.
func (c *FakeCephSources) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CephSourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cephsourcesResource, cephsourcesKind, c.ns, opts), &v1alpha1.CephSourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CephSourceList{ListMeta: obj.(*v1alpha1.CephSourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.CephSourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cephSources.
func (c *FakeCephSources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cephsourcesResource, c.ns, opts))

}

// Create takes the representation of a cephSource and creates it.  Returns the server's representation of the cephSource, and an error, if there is any.
func (c *FakeCephSources) Create(ctx context.Context, cephSource *v1alpha1.CephSource, opts v1.CreateOptions) (result *v1alpha1.CephSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cephsourcesResource, c.ns, cephSource), &v1alpha1.CephSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CephSource), err
}

// Update takes the representation of a cephSource and updates it. Returns the server's representation of the cephSource, and an error, if there is any.
func (c *FakeCephSources) Update(ctx context.Context, cephSource *v1alpha1.CephSource, opts v1.UpdateOptions) (result *v1alpha1.CephSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cephsourcesResource, c.ns, cephSource), &v1alpha1.CephSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CephSource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCephSources) UpdateStatus(ctx context.Context, cephSource *v1alpha1.CephSource, opts v1.UpdateOptions) (*v1alpha1.CephSource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(cephsourcesResource, "status", c.ns, cephSource), &v1alpha1.CephSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CephSource), err
}

// Delete takes name of the cephSource and deletes it. Returns an error if one occurs.
func (c *FakeCephSources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(cephsourcesResource, c.ns, name), &v1alpha1.CephSource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCephSources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cephsourcesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CephSourceList{})
	return err
}

// Patch applies the patch and returns the patched cephSource.
func (c *FakeCephSources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CephSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cephsourcesResource, c.ns, name, pt, data, subresources...), &v1alpha1.CephSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CephSource), err
}
