apiVersion: eventing.knative.dev/v1alpha1
kind: Channel
metadata:
  name: gitlabchannel
spec:
  provisioner:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: ClusterChannelProvisioner
    name: in-memory-channel

---

apiVersion: sources.eventing.triggermesh.dev/v1alpha1
kind: GitLabSource
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: gitlabsource-sample
spec:
  eventTypes:
  - push_events
  - issues_events
  projectUrl: "https://gitlab.com/murali-reddy/gitlabsource"
  accessToken:
    secretKeyRef:
      name: gitlabsecret
      key: accessToken
  secretToken:
    secretKeyRef:
      name: gitlabsecret
      key: secretToken
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: gitlabchannel

