apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSources
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: containersources-sample
spec:
  image: github.com/knative/eventing-sources/cmd/heartbeats/
  args:
   - '--label="<3"'
   - '--period=2'
