apiVersion: sources.eventing.knative.dev/v1alpha1
kind: KubernetesEventSource
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: kuberneteseventsource-sample
spec:
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: foo-channel
