apiVersion: bindings.knative.dev/v1alpha1
kind: GitLabBinding
metadata:
  name: gitlab-binding
spec:
  subject:
    apiVersion: apps/v1
    kind: Deployment
    selector:
      matchLabels:
        gitlabbinding: "true"

  accessToken:
    secretKeyRef:
      name: gitlabsecret
      key: accessToken
