# Apache Camel Chuck Source
#
# A variant of the Http Poller source that parses and transforms JSON data (random sentences about Chuck Norris).
#
# Timer Component documentation: https://camel.apache.org/components/latest/timer-component.html
# Http Component documentation: https://camel.apache.org/components/latest/http-component.html
# Json Jackson data format documentation: https://camel.apache.org/components/latest/json-jackson-dataformat.html
# Simple language documentation: https://camel.apache.org/manual/latest/simple-language.html
#
# List of available Apache Camel components: https://camel.apache.org/components/latest/
#
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: CamelSource
metadata:
  name: camel-chuck-source
spec:
  source:
    flow:
      from:
        uri: timer:tick
        parameters:
          period: 10s
        steps:
          - to: http://api.icndb.com/jokes/random?exclude=[explicit]
          - unmarshal:
              json: {}
          - transform:
              simple: "${body[value][joke]}"
          - set-header:
              name: ce-source
              constant: camel-chuck-source
          - set-header:
              name: ce-type
              constant: chuck.camel.apache.org
          - set-header:
              name: ce-specversion
              constant: "0.3"
          - set-header:
              name: Content-Type
              constant: text/plain
          - log:
              message: "Sending: ${body}"
    integration:
      dependencies:
        - camel:jackson
  sink:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: InMemoryChannel
    name: camel-test
