# Apache Camel Timer Source
#
# Timer Component documentation: https://github.com/apache/camel/blob/master/camel-core/src/main/docs/timer-component.adoc
#
# List of available Apache Camel components: https://github.com/apache/camel/tree/master/components
#
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: CamelSource
metadata:
  name: camel-timer-flow-source
spec:
  source:
    flow: |
      from:
        uri: timer:tick?period=3s
        steps:
          - set-body:
              constant: Hello world!
  sink:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: Channel
    name: camel-test
