/*
Copyright 2018 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/knative/eventing-sources/contrib/bitbucket/pkg/apis/sources/v1alpha1"
	scheme "github.com/knative/eventing-sources/contrib/bitbucket/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// BitBucketSourcesGetter has a method to return a BitBucketSourceInterface.
// A group's client should implement this interface.
type BitBucketSourcesGetter interface {
	BitBucketSources(namespace string) BitBucketSourceInterface
}

// BitBucketSourceInterface has methods to work with BitBucketSource resources.
type BitBucketSourceInterface interface {
	Create(*v1alpha1.BitBucketSource) (*v1alpha1.BitBucketSource, error)
	Update(*v1alpha1.BitBucketSource) (*v1alpha1.BitBucketSource, error)
	UpdateStatus(*v1alpha1.BitBucketSource) (*v1alpha1.BitBucketSource, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.BitBucketSource, error)
	List(opts v1.ListOptions) (*v1alpha1.BitBucketSourceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.BitBucketSource, err error)
	BitBucketSourceExpansion
}

// bitBucketSources implements BitBucketSourceInterface
type bitBucketSources struct {
	client rest.Interface
	ns     string
}

// newBitBucketSources returns a BitBucketSources
func newBitBucketSources(c *SourcesV1alpha1Client, namespace string) *bitBucketSources {
	return &bitBucketSources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the bitBucketSource, and returns the corresponding bitBucketSource object, and an error if there is any.
func (c *bitBucketSources) Get(name string, options v1.GetOptions) (result *v1alpha1.BitBucketSource, err error) {
	result = &v1alpha1.BitBucketSource{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("bitbucketsources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of BitBucketSources that match those selectors.
func (c *bitBucketSources) List(opts v1.ListOptions) (result *v1alpha1.BitBucketSourceList, err error) {
	result = &v1alpha1.BitBucketSourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("bitbucketsources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested bitBucketSources.
func (c *bitBucketSources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("bitbucketsources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a bitBucketSource and creates it.  Returns the server's representation of the bitBucketSource, and an error, if there is any.
func (c *bitBucketSources) Create(bitBucketSource *v1alpha1.BitBucketSource) (result *v1alpha1.BitBucketSource, err error) {
	result = &v1alpha1.BitBucketSource{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("bitbucketsources").
		Body(bitBucketSource).
		Do().
		Into(result)
	return
}

// Update takes the representation of a bitBucketSource and updates it. Returns the server's representation of the bitBucketSource, and an error, if there is any.
func (c *bitBucketSources) Update(bitBucketSource *v1alpha1.BitBucketSource) (result *v1alpha1.BitBucketSource, err error) {
	result = &v1alpha1.BitBucketSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("bitbucketsources").
		Name(bitBucketSource.Name).
		Body(bitBucketSource).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *bitBucketSources) UpdateStatus(bitBucketSource *v1alpha1.BitBucketSource) (result *v1alpha1.BitBucketSource, err error) {
	result = &v1alpha1.BitBucketSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("bitbucketsources").
		Name(bitBucketSource.Name).
		SubResource("status").
		Body(bitBucketSource).
		Do().
		Into(result)
	return
}

// Delete takes name of the bitBucketSource and deletes it. Returns an error if one occurs.
func (c *bitBucketSources) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("bitbucketsources").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *bitBucketSources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("bitbucketsources").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched bitBucketSource.
func (c *bitBucketSources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.BitBucketSource, err error) {
	result = &v1alpha1.BitBucketSource{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("bitbucketsources").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
