/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "knative.dev/eventing-contrib/gitlab/pkg/apis/bindings/v1alpha1"
	scheme "knative.dev/eventing-contrib/gitlab/pkg/client/clientset/versioned/scheme"
)

// GitLabBindingsGetter has a method to return a GitLabBindingInterface.
// A group's client should implement this interface.
type GitLabBindingsGetter interface {
	GitLabBindings(namespace string) GitLabBindingInterface
}

// GitLabBindingInterface has methods to work with GitLabBinding resources.
type GitLabBindingInterface interface {
	Create(ctx context.Context, gitLabBinding *v1alpha1.GitLabBinding, opts v1.CreateOptions) (*v1alpha1.GitLabBinding, error)
	Update(ctx context.Context, gitLabBinding *v1alpha1.GitLabBinding, opts v1.UpdateOptions) (*v1alpha1.GitLabBinding, error)
	UpdateStatus(ctx context.Context, gitLabBinding *v1alpha1.GitLabBinding, opts v1.UpdateOptions) (*v1alpha1.GitLabBinding, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.GitLabBinding, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.GitLabBindingList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GitLabBinding, err error)
	GitLabBindingExpansion
}

// gitLabBindings implements GitLabBindingInterface
type gitLabBindings struct {
	client rest.Interface
	ns     string
}

// newGitLabBindings returns a GitLabBindings
func newGitLabBindings(c *BindingsV1alpha1Client, namespace string) *gitLabBindings {
	return &gitLabBindings{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the gitLabBinding, and returns the corresponding gitLabBinding object, and an error if there is any.
func (c *gitLabBindings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GitLabBinding, err error) {
	result = &v1alpha1.GitLabBinding{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("gitlabbindings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GitLabBindings that match those selectors.
func (c *gitLabBindings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GitLabBindingList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.GitLabBindingList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("gitlabbindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested gitLabBindings.
func (c *gitLabBindings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("gitlabbindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a gitLabBinding and creates it.  Returns the server's representation of the gitLabBinding, and an error, if there is any.
func (c *gitLabBindings) Create(ctx context.Context, gitLabBinding *v1alpha1.GitLabBinding, opts v1.CreateOptions) (result *v1alpha1.GitLabBinding, err error) {
	result = &v1alpha1.GitLabBinding{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("gitlabbindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(gitLabBinding).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a gitLabBinding and updates it. Returns the server's representation of the gitLabBinding, and an error, if there is any.
func (c *gitLabBindings) Update(ctx context.Context, gitLabBinding *v1alpha1.GitLabBinding, opts v1.UpdateOptions) (result *v1alpha1.GitLabBinding, err error) {
	result = &v1alpha1.GitLabBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("gitlabbindings").
		Name(gitLabBinding.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(gitLabBinding).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *gitLabBindings) UpdateStatus(ctx context.Context, gitLabBinding *v1alpha1.GitLabBinding, opts v1.UpdateOptions) (result *v1alpha1.GitLabBinding, err error) {
	result = &v1alpha1.GitLabBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("gitlabbindings").
		Name(gitLabBinding.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(gitLabBinding).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the gitLabBinding and deletes it. Returns an error if one occurs.
func (c *gitLabBindings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("gitlabbindings").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *gitLabBindings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("gitlabbindings").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched gitLabBinding.
func (c *gitLabBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GitLabBinding, err error) {
	result = &v1alpha1.GitLabBinding{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("gitlabbindings").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
