apiVersion: v1
kind: ServiceAccount
metadata:
  name: awssqs
secrets:
- name: awssqs-source-key
---
apiVersion: v1
kind: Secret
metadata:
  name: awssqs-source-key
type: Opaque
data:
  'key.json': ""
