apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ApiServerSource
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: apiserversource-sample
spec:
  serviceAccountName: apiserver-event-source-sample
  resources:
    - apiVersion: v1
      kind: ConfigMap
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: event-display
