---
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  name: ibm-mq
spec:
  template:
    spec:
      containers:
        - image: github.com/triggermesh/eventing-contrib/contrib/ibm-mq
          name: receiver
          env:
            - name: LD_LIBRARY_PATH
              value: /var/run/ko/lib64
            - name: QUEUE_MANAGER
              value: QM1
            - name: CHANNEL_NAME
              value: DEV.APP.SVRCONN
            - name: CONNECTION_NAME
              value: mq-service.default.svc.cluster.local(1414)
            - name: QUEUE_NAME
              value: DEV.QUEUE.1
            - name: USER_ID
              value: <USER_ID>
            - name: PASSWORD
              value: <PASSWORD>
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: default
