# Copyright 2019 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: githubsources.sources.eventing.knative.dev
  labels:
    contrib.eventing.knative.dev/release: devel
    eventing.knative.dev/source: "true"
    knative.dev/crd-install: "true"
spec:
  group: sources.eventing.knative.dev
  names:
    categories:
    - all
    - knative
    - eventing
    - sources
    kind: GitHubSource
    plural: githubsources
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        registry:
          type: object
          description: "Internal information, users should not set this property"
          properties:
            eventTypes:
              # TODO: set the schemas.
              type: object
              description: "Event types that GitHubSource can produce"
              properties:
                check_suite:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.check_suite"
                    schema:
                      type: string
                      pattern: ""
                commit_comment:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.commit_comment"
                    schema:
                      type: string
                      pattern: ""
                create:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.create"
                    schema:
                      type: string
                      pattern: ""
                delete:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.delete"
                    schema:
                      type: string
                      pattern: ""
                deployment:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.deployment"
                    schema:
                      type: string
                      pattern: ""
                deployment_status:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.deployment_status"
                    schema:
                      type: string
                      pattern: ""
                fork:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.fork"
                    schema:
                      type: string
                      pattern: ""
                gollum:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.gollum"
                    schema:
                      type: string
                      pattern: ""
                installation:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.installation"
                    schema:
                      type: string
                      pattern: ""
                integration_installation:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.integration_installation"
                    schema:
                      type: string
                      pattern: ""
                issue_comment:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.issue_comment"
                    schema:
                      type: string
                      pattern: ""
                issues:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.issues"
                    schema:
                      type: string
                      pattern: ""
                label:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.label"
                    schema:
                      type: string
                      pattern: ""
                member:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.member"
                    schema:
                      type: string
                      pattern: ""
                membership:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.membership"
                    schema:
                      type: string
                      pattern: ""
                milestone:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.milestone"
                    schema:
                      type: string
                      pattern: ""
                organization:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.organization"
                    schema:
                      type: string
                      pattern: ""
                org_block:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.org_block"
                    schema:
                      type: string
                      pattern: ""
                page_build:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.page_build"
                    schema:
                      type: string
                      pattern: ""
                ping:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.ping"
                    schema:
                      type: string
                      pattern: ""
                project_card:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.project_card"
                    schema:
                      type: string
                      pattern: ""
                project_column:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.project_column"
                    schema:
                      type: string
                      pattern: ""
                project:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.project"
                    schema:
                      type: string
                      pattern: ""
                public:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.public"
                    schema:
                      type: string
                      pattern: ""
                pull_request:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.pull_request"
                    schema:
                      type: string
                      pattern: ""
                pull_request_review:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.pull_request_review"
                    schema:
                      type: string
                      pattern: ""
                pull_request_review_comment:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.pull_request_review_comment"
                    schema:
                      type: string
                      pattern: ""
                push:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.push"
                    schema:
                      type: string
                      pattern: ""
                release:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.release"
                    schema:
                      type: string
                      pattern: ""
                repository:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.repository"
                    schema:
                      type: string
                      pattern: ""
                status:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.status"
                    schema:
                      type: string
                      pattern: ""
                team:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.team"
                    schema:
                      type: string
                      pattern: ""
                team_add:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.team_add"
                    schema:
                      type: string
                      pattern: ""
                watch:
                  type: object
                  properties:
                    type:
                      type: string
                      pattern: "dev.knative.source.github.watch"
                    schema:
                      type: string
                      pattern: ""
        spec:
          properties:
            accessToken:
              properties:
                secretKeyRef:
                  type: object
              type: object
            eventTypes:
              items:
                enum:
                - check_suite
                - commit_comment
                - create
                - delete
                - deployment
                - deployment_status
                - fork
                - gollum
                - installation
                - integration_installation
                - issue_comment
                - issues
                - label
                - member
                - membership
                - milestone
                - organization
                - org_block
                - page_build
                - ping
                - project_card
                - project_column
                - project
                - public
                - pull_request
                - pull_request_review
                - pull_request_review_comment
                - push
                - release
                - repository
                - status
                - team
                - team_add
                - watch
                type: string
              minItems: 1
              type: array
            ownerAndRepository:
              minLength: 1
              type: string
            secretToken:
              properties:
                secretKeyRef:
                  type: object
              type: object
            serviceAccountName:
              type: string
            sink:
              type: object
          required:
          - ownerAndRepository
          - eventTypes
          - accessToken
          - secretToken
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    # we use a string in the stored object but a wrapper object
                    # at runtime.
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  severity:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            sinkUri:
              type: string
            webhookIDKey:
              type: string
          type: object
  version: v1alpha1
