/*
Copyright 2019 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "knative.dev/eventing-contrib/couchdb/importer/pkg/apis/sources/v1alpha1"
)

// FakeCouchDbImporters implements CouchDbImporterInterface
type FakeCouchDbImporters struct {
	Fake *FakeSourcesV1alpha1
	ns   string
}

var couchdbimportersResource = schema.GroupVersionResource{Group: "sources.eventing.knative.dev", Version: "v1alpha1", Resource: "couchdbimporters"}

var couchdbimportersKind = schema.GroupVersionKind{Group: "sources.eventing.knative.dev", Version: "v1alpha1", Kind: "CouchDbImporter"}

// Get takes name of the couchDbImporter, and returns the corresponding couchDbImporter object, and an error if there is any.
func (c *FakeCouchDbImporters) Get(name string, options v1.GetOptions) (result *v1alpha1.CouchDbImporter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(couchdbimportersResource, c.ns, name), &v1alpha1.CouchDbImporter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CouchDbImporter), err
}

// List takes label and field selectors, and returns the list of CouchDbImporters that match those selectors.
func (c *FakeCouchDbImporters) List(opts v1.ListOptions) (result *v1alpha1.CouchDbImporterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(couchdbimportersResource, couchdbimportersKind, c.ns, opts), &v1alpha1.CouchDbImporterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CouchDbImporterList{ListMeta: obj.(*v1alpha1.CouchDbImporterList).ListMeta}
	for _, item := range obj.(*v1alpha1.CouchDbImporterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested couchDbImporters.
func (c *FakeCouchDbImporters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(couchdbimportersResource, c.ns, opts))

}

// Create takes the representation of a couchDbImporter and creates it.  Returns the server's representation of the couchDbImporter, and an error, if there is any.
func (c *FakeCouchDbImporters) Create(couchDbImporter *v1alpha1.CouchDbImporter) (result *v1alpha1.CouchDbImporter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(couchdbimportersResource, c.ns, couchDbImporter), &v1alpha1.CouchDbImporter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CouchDbImporter), err
}

// Update takes the representation of a couchDbImporter and updates it. Returns the server's representation of the couchDbImporter, and an error, if there is any.
func (c *FakeCouchDbImporters) Update(couchDbImporter *v1alpha1.CouchDbImporter) (result *v1alpha1.CouchDbImporter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(couchdbimportersResource, c.ns, couchDbImporter), &v1alpha1.CouchDbImporter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CouchDbImporter), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCouchDbImporters) UpdateStatus(couchDbImporter *v1alpha1.CouchDbImporter) (*v1alpha1.CouchDbImporter, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(couchdbimportersResource, "status", c.ns, couchDbImporter), &v1alpha1.CouchDbImporter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CouchDbImporter), err
}

// Delete takes name of the couchDbImporter and deletes it. Returns an error if one occurs.
func (c *FakeCouchDbImporters) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(couchdbimportersResource, c.ns, name), &v1alpha1.CouchDbImporter{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCouchDbImporters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(couchdbimportersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.CouchDbImporterList{})
	return err
}

// Patch applies the patch and returns the patched couchDbImporter.
func (c *FakeCouchDbImporters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CouchDbImporter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(couchdbimportersResource, c.ns, name, data, subresources...), &v1alpha1.CouchDbImporter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CouchDbImporter), err
}
